/**
 * O'zbekiston viloyatlari va tumanlari
 */

export const regions = [
  {
    id: 'tashkent',
    name: 'Toshkent',
    districts: [
      'Bektemir',
      'Mirobod',
      'Mirzo-Ulug\'bek',
      'Olmazor',
      'Sergeli',
      'Shayxontohur',
      'Uchtepa',
      'Yakkasaroy',
      'Yashnobod',
      'Yunusobod',
      'Chilonzor',
    ],
  },
  {
    id: 'andijan',
    name: 'Andijon',
    districts: [
      'Andijon shahri',
      'Andijon tumani',
      'Asaka',
      'Baliqchi',
      'Bo\'z',
      'Buloqboshi',
      'Izboskan',
      'Jalaquduq',
      'Qo\'rg\'ontepa',
      'Paxtaobod',
      'Ulug\'nor',
      'Xonobod',
      'Shahrixon',
    ],
  },
  {
    id: 'bukhara',
    name: 'Buxoro',
    districts: [
      'Buxoro shahri',
      'Buxoro tumani',
      'Vobkent',
      'G\'ijduvon',
      'Jondor',
      'Kogon',
      'Olot',
      'Peshku',
      'Qorako\'l',
      'Qorovulbozor',
      'Romitan',
      'Shofirkon',
    ],
  },
  {
    id: 'fergana',
    name: 'Farg\'ona',
    districts: [
      'Farg\'ona shahri',
      'Farg\'ona tumani',
      'Beshariq',
      'Bog\'dod',
      'Buvayda',
      'Dang\'ara',
      'Furqat',
      'Qo\'qon',
      'Qo\'shtepa',
      'Rishton',
      'So\'x',
      'Toshloq',
      'Uchko\'prik',
      'O\'zbekiston',
      'Yozyovon',
    ],
  },
  {
    id: 'jizzakh',
    name: 'Jizzax',
    districts: [
      'Jizzax shahri',
      'Jizzax tumani',
      'Arnasoy',
      'Baxmal',
      'Do\'stlik',
      'Forish',
      'G\'allaorol',
      'Mirzacho\'l',
      'Paxtakor',
      'Yangiobod',
      'Zarbdor',
      'Zafarobod',
      'Zomin',
    ],
  },
  {
    id: 'qashqadaryo',
    name: 'Qashqadaryo',
    districts: [
      'Qarshi shahri',
      'Qarshi tumani',
      'Chiroqchi',
      'Dehqonobod',
      'G\'uzor',
      'Kasbi',
      'Kitob',
      'Koson',
      'Mirishkor',
      'Muborak',
      'Nishon',
      'Qamashi',
      'Shahrisabz',
      'Yakkabog\'',
    ],
  },
  {
    id: 'navoiy',
    name: 'Navoiy',
    districts: [
      'Navoiy shahri',
      'Navoiy tumani',
      'Karmana',
      'Konimex',
      'Nurota',
      'Qiziltepa',
      'Tomdi',
      'Uchquduq',
      'Xatirchi',
      'Zarafshon',
    ],
  },
  {
    id: 'namangan',
    name: 'Namangan',
    districts: [
      'Namangan shahri',
      'Namangan tumani',
      'Kosonsoy',
      'Mingbuloq',
      'Norin',
      'Pop',
      'To\'raqo\'rg\'on',
      'Uchqo\'rg\'on',
      'Uychi',
      'Chortoq',
      'Chust',
      'Yangiqo\'rg\'on',
    ],
  },
  {
    id: 'samarkand',
    name: 'Samarqand',
    districts: [
      'Samarqand shahri',
      'Samarqand tumani',
      'Bulung\'ur',
      'Jomboy',
      'Ishtixon',
      'Kattaqo\'rg\'on',
      'Narpay',
      'Nurobod',
      'Oqdaryo',
      'Paxtachi',
      'Payariq',
      'Pastdarg\'om',
      'Qo\'shrabot',
      'Toyloq',
      'Urgut',
    ],
  },
  {
    id: 'surkhandaryo',
    name: 'Surxondaryo',
    districts: [
      'Termiz shahri',
      'Termiz tumani',
      'Angor',
      'Bandixon',
      'Boysun',
      'Denov',
      'Jarqo\'rg\'on',
      'Qiziriq',
      'Qumqo\'rg\'on',
      'Muzrabot',
      'Oltinsoy',
      'Sariosiyo',
      'Sho\'rchi',
      'Uzun',
    ],
  },
  {
    id: 'sirdaryo',
    name: 'Sirdaryo',
    districts: [
      'Guliston shahri',
      'Guliston tumani',
      'Boyovut',
      'Guliston',
      'Mirzaobod',
      'Oqoltin',
      'Sayxunobod',
      'Sardoba',
      'Sirdaryo',
      'Xavos',
      'Yangiyer',
    ],
  },
  {
    id: 'tashkent-region',
    name: 'Toshkent viloyati',
    districts: [
      'Angren',
      'Bekobod',
      'Bo\'ka',
      'Bo\'stonliq',
      'Chinoz',
      'O\'rta Chirchiq',
      'Ohangaron',
      'Parkent',
      'Piskent',
      'Qibray',
      'Quyi Chirchiq',
      'Yangiyo\'l',
      'Yuqori Chirchiq',
      'Zangiota',
    ],
  },
  {
    id: 'khorezm',
    name: 'Xorazm',
    districts: [
      'Urganch shahri',
      'Urganch tumani',
      'Bog\'ot',
      'Gurlan',
      'Qo\'shko\'pir',
      'Shovot',
      'Tuproqqal\'a',
      'Xazorasp',
      'Xiva',
      'Xonqa',
      'Yangiariq',
      'Yangibozor',
    ],
  },
  {
    id: 'karakalpakstan',
    name: 'Qoraqalpog\'iston',
    districts: [
      'Nukus shahri',
      'Nukus tumani',
      'Amudaryo',
      'Beruniy',
      'Chimboy',
      'Ellikqal\'a',
      'Kegeyli',
      'Mo\'ynoq',
      'Nukus',
      'Qanliko\'l',
      'Qo\'ng\'irot',
      'Qorao\'zak',
      'Shumanay',
      'Taxtako\'pir',
      'To\'rtko\'l',
      'Xo\'jayli',
    ],
  },
] as const;

export type RegionId = (typeof regions)[number]['id'];
export type DistrictName = string;

